version: '3'
services:
  frontend:
    build: ./
    container_name: portfolio-frontend
    image: portfolio-frontend
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app/
      - portfolio-frontend-node_modules:/usr/src/app/node_modules
volumes:
  portfolio-frontend-node_modules:
